version: '3.8'

services:
  django:
    build: .
    command: gunicorn readme.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    networks:
      - mynetwork  # Define a network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork  # Connect to the same network

networks:
  mynetwork:  # Define the network for both services